services:
  - type: web
    name: sehat-iqra-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /api/v1/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
