
# The message you pass when running alembic revision -m "Your message".
# 6315ffccc3ec: A unique ID for this migration, usually a hash  
# None: The ID(s) of the parent migration(s). Alembic uses this to understand the migration history chain.
# 2025-08-04 09:17:03.444541: Timestamp of when the migration was generated.

"""initial migration
Revision ID: 6315ffccc3ec
Revises: 
Create Date: 2025-08-04 09:17:03.444541
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# These lines act as metadata — telling Alembic where this migration belongs in the overall database version history.
revision: str = '6315ffccc3ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
