
# The message you pass when running alembic revision -m "Your message".
# 7538e9486efe: A unique ID for this migration, usually a hash  
# 9bfd9d0dd7a6: The ID(s) of the parent migration(s). Alembic uses this to understand the migration history chain.
# 2025-08-08 10:04:08.290076: Timestamp of when the migration was generated.

"""Add role column
Revision ID: 7538e9486efe
Revises: 9bfd9d0dd7a6
Create Date: 2025-08-08 10:04:08.290076
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# These lines act as metadata — telling Alembic where this migration belongs in the overall database version history.
revision: str = '7538e9486efe'
down_revision: Union[str, Sequence[str], None] = '9bfd9d0dd7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
