
# The message you pass when running alembic revision -m "Your message".
# 9bfd9d0dd7a6: A unique ID for this migration, usually a hash  
# 6315ffccc3ec: The ID(s) of the parent migration(s). Alembic uses this to understand the migration history chain.
# 2025-08-05 05:11:48.099328: Timestamp of when the migration was generated.

"""Add token_blacklist table
Revision ID: 9bfd9d0dd7a6
Revises: 6315ffccc3ec
Create Date: 2025-08-05 05:11:48.099328
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# These lines act as metadata — telling Alembic where this migration belongs in the overall database version history.
revision: str = '9bfd9d0dd7a6'
down_revision: Union[str, Sequence[str], None] = '6315ffccc3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
