"""Added column hospital_name

Revision ID: 4b593a970438
Revises: a3635d81bf55
Create Date: 2025-08-07 16:30:11.370239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b593a970438'
down_revision: Union[str, Sequence[str], None] = 'a3635d81bf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('hospital_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'hospital_name')
    # ### end Alembic commands ###
