"""Add resources table

Revision ID: a3635d81bf55
Revises: 
Create Date: 2025-08-07 07:21:22.119577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3635d81bf55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('icu_beds', sa.Integer(), nullable=False),
        sa.Column('ventilators', sa.Integer(), nullable=False),
        sa.Column('monitors', sa.Integer(), nullable=False),
        sa.Column('defibrillators', sa.Integer(), nullable=False),
        sa.Column('infusion_pumps', sa.Integer(), nullable=False),
        sa.Column('oxygen_cylinders', sa.Integer(), nullable=False),
        sa.Column('xray_machines', sa.Integer(), nullable=False),
        sa.Column('ultrasound_machines', sa.Integer(), nullable=False),
        sa.Column('ct_scanners', sa.Integer(), nullable=False),
        sa.Column('mri_machines', sa.Integer(), nullable=False),
        sa.Column('ecg_machines', sa.Integer(), nullable=False),
        sa.Column('dialysis_machines', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###