"""Add hospital_username column

Revision ID: f465f041225a
Revises: 4b593a970438
Create Date: 2025-08-11 06:24:13.152854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f465f041225a'
down_revision: Union[str, Sequence[str], None] = '4b593a970438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('hospital_username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'hospital_username')
    # ### end Alembic commands ###
